update docker-build-release workflow

diff --git a/.github/workflows/docker-build-release.yaml b/.github/workflows/docker-build-release.yaml
--- a/.github/workflows/docker-build-release.yaml
+++ b/.github/workflows/docker-build-release.yaml
@@ -8,16 +8,21 @@ on:
         description: 'Image name. If empty, use repository name'
         required: false
         default: ''
-      tags:
-        description: 'Tags'
-        required: false
-        type: string
-        default: ''
       dry-run:
         description: 'Dry run'
         required: false
         type: boolean
         default: false
+      version-type:
+        description: 'Version type to release'
+        type: choice
+        options:
+          - 'major'
+          - 'minor'
+          - 'patch'
+        required: true
+        default: 'patch'
+
   push:
     branches:
       - '**'
@@ -47,6 +52,44 @@ env:
   PLATFORMS: linux/amd64,linux/arm64
 
 jobs:
+  load-docker-build-components:
+    runs-on: ubuntu-latest
+    outputs:
+      component: ${{ steps.load_component.outputs.components }}
+      platforms: ${{ steps.load_component.outputs.platforms }}
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
+        with:
+          persist-credentials: false
+
+      - name: Load Docker Configuration
+        id: load_component
+        run: |
+          verify=$(cat "$GITHUB_WORKSPACE/.github/docker-build-config.json" | jq '
+          def verify_structure:
+          .components as $components
+          | .platforms as $platforms
+          | ($components | type == "array")
+          and (all($components[]; has("name") and has("file") and has("context")))
+          and ($platforms | type == "string");
+          verify_structure
+          | if . then true else false end
+          ')
+          if [ ${verify} == 'true' ]; then
+            echo "✅ $GITHUB_WORKSPACE/.github/docker-build-config.json file is valid"
+            components=$(jq -c ".components" "$GITHUB_WORKSPACE/.github/docker-build-config.json")
+            platforms=$(jq -c ".platforms" "$GITHUB_WORKSPACE/.github/docker-build-config.json")
+          else
+            echo "❗ $GITHUB_WORKSPACE/.github/docker-build-config.json file is invalid"
+            echo "❗ $GITHUB_WORKSPACE/.github/docker-build-config.json file is invalid" >> $GITHUB_STEP_SUMMARY
+            exit 1
+          fi
+          echo "components=${components}" >> $GITHUB_OUTPUT
+          echo "platforms=${platforms}" >> $GITHUB_OUTPUT
+          echo "components=${components}"
+          echo "platforms=${platforms}"
+
   docker-build:
     name: "Build and Publish Docker Image"
     permissions:
@@ -62,34 +105,45 @@ jobs:
         with:
           persist-credentials: false
 
-      - name: "Create name"
-        uses: netcracker/qubership-workflow-hub/actions/metadata-action@b575bad3a0959c4e883bc34f9d055ff07fde2dbd # v1.0.7
-        id: metadata
-
       - name: "Prepare tags"
         id: prepare_tags
         run: |
-          BASE_TAG="${{ steps.metadata.outputs.result }}"
-          EXTRA_TAG="${{ github.event.inputs.tags }}"
-          if [ -n "$EXTRA_TAG" ]; then
-            TAGS="${BASE_TAG}, ${EXTRA_TAG}"
+          echo "Check current tag"
+          TAG=$(git tag --list --sort=-v:refname | head -n 1)
+          echo "Сurrent tag: $TAG"
+
+          if [[ -z "$TAG" ]]; then
+            NEW_TAG="1.0.0"
           else
-            TAGS="${BASE_TAG}"
+            MAJOR=$(echo $TAG | cut -d. -f1)
+            MINOR=$(echo $TAG | cut -d. -f2)
+            PATCH=$(echo $TAG | cut -d. -f3)
+            PATCH=$((PATCH + 1))
+            NEW_TAG="$MAJOR.$MINOR.$PATCH"
           fi
-          echo "tags=${TAGS}" >> $GITHUB_OUTPUT
+
+          echo "new_tag=$NEW_TAG" >> $GITHUB_OUTPUT
+          echo "New version will be: $NEW_TAG"
 
       - name: "Summary step"
         run: |
-          echo "**Metadata:** ${{ steps.metadata.outputs.result }}" >> $GITHUB_STEP_SUMMARY
-          echo "**Tags:** ${{ steps.prepare_tags.outputs.tags }}" >> $GITHUB_STEP_SUMMARY
+          echo "**Tags:** ${{ steps.prepare_tags.outputs.new_tag }}" >> $GITHUB_STEP_SUMMARY
 
-      - name: "Build and Publish Docker Image"
-        uses: netcracker/qubership-workflow-hub/actions/docker-action@b575bad3a0959c4e883bc34f9d055ff07fde2dbd #v1.0.7
+      - name: Build and Publish Docker Image
+        uses: netcracker/qubership-workflow-hub/actions/docker-action@396774180000abdb825cbf150b56cc59c6913db8 #v2.0.5
         with:
-          custom-image-name: ${{ github.event.inputs.custom-image-name || '' }}
-          platforms: ${{ env.PLATFORMS }}
-          checkout: "false"
-          tags: ${{ steps.prepare_tags.outputs.tags }}
-          dry-run: ${{ github.event.inputs.dry-run || 'false' }}
+          ref: ${{ github.ref }}
+          tags: ${{ steps.prepare_tags.outputs.new_tag }}
+          component: ${{ toJson(matrix.component) }}
+          platforms: ${{ needs.load-docker-build-components.outputs.platforms }}
+          dry-run: false
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+  github-release:
+    needs: [docker-build]
+    if: ${{ needs.docker-build.result == 'success' }}
+    uses: netcracker/qubership-workflow-hub/.github/workflows/release-drafter.yml@396774180000abdb825cbf150b56cc59c6913db8 #v2.0.5
+    with:
+      version: ${{ needs.prepare_tags.outputs.new_tag }}
+      publish: true
